### ISSUE TITLE
add project to Projects using Docile / Lexicon

### ISSUE THREAD

**Issue by peter1000** [lendle/TargetedLearning.jl#4]
hi,

Are you still using Docile/Lexicon for documentation. If so 
I would like to add your project to [Projects using Docile / Lexicon](https://github.com/MichaelHatherly/Docile.jl#projects-using-docile--lexicon)
if that is fine with you.

Thanks.

**Comment by lendle** [comment]
Please do, thanks!

**Comment by peter1000** [comment]
do you habe any other projects which use Docile / Lexicon I may add also?

**Comment by lendle** [comment]
That's it for now.
